### PR TITLE
Adding snap

### PR DESCRIPTION
**Pull request by natalytvinova**
Added trident snapcraft file for creating a snap for Trident. 
A snap is an automatically updated bundle of an app and its dependencies that
works without modification across many different Linux distributions. 
Snaps simplify installs to a single standard command: 
`$ sudo snap install tridentctl`

### CODE REVIEW

**Comment by korenaren** [comment]
Hi @natalytvinova - have you submitted the CCLA to NetApp Legal? (https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md)

**Comment by CalvinHartwell** [comment]
@korenaren thanks for the speedy response, we are reviewing the CCLA with our legal team right now, I don't think it will be an issue.

**Comment by natalytvinova** [comment]
@korenaren I sent the signed agreement to NetApp Legal today.

**Comment by CalvinHartwell** [comment]
@korenaren the CCLA has been signed from our side, hopefully it should be sorted out now.

**Comment by korenaren** [comment]
Thanks. I will get someone to take a look at this, not sure about the timing though, so please bear with us.

**Comment by natalytvinova** [comment]
@korenaren Hi! Is there any update on this?

**Comment by korenaren** [comment]
Unfortunately, no. I'm trying to learn more about if we need to, and how we would integrate this into our CI platform. Seems like we also need to account for maintenance across Trident releases.

**Comment by CalvinHartwell** [comment]
Hi @korenaren, 

Has there been any progress on this? We have more customer requests and we had hoped that we could create a blog post for this. Canonical's CI will automatically build the snap and make it available publicly on the snap store to provide an alternative, auto-updating mechanism for distributing the software. 

On Ubuntu and Ubuntu derivatives using snaps, it would be as simple as: 

```
sudo snap install netapp-trident`
```

Then the software would be ready to use and it would receive automatic minor updates. 

Cheers

**Comment by gnarl** [comment]
Hi @CalvinHartwell,

We appreciate the contribution but we are not able to add support for snap and maintain it across Trident releases at this time.

**Pull request closed without merging**
