### PR TITLE
Use Kubernetes CRDs as persistent storage

### PR DESCRIPTION
**Pull request by ThatsMrTalbot**
Add support for trident to use Kubernetes CRD objects to store persistent state.

**Context**
Similar projects like Calico that require persistent state also allow the Kubernetes API itself to be used to store this state. This is done through Kubernetes CRD objects. This removes the issue of having to migrate an etcd onto storage as a bootstrap step, as Kubernetes already has persistent storage.

https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

**Implementation**
- Kubernetes style objects have been defined 
- The Kubernetes client API is autogenerated with https://github.com/kubernetes/code-generator
- A fake client is also generated for writing tests against
- The code generated client is used in a persistent storage implementation
- Tests are written against the fake client generated by Kubernetes codegen
- Test are also written against the conversion functions for CRD->internal and internal->CRD
- Since only one of these should be running per cluster, a Mutex is used to do more atomic updates

### CODE REVIEW

**Comment by kangarlou** [comment]
@ThatsMrTalbot We appreciate the time and effort you've put into this PR! We're familiar with CRDs and have investigated their applications in existing and new Trident workflows (e.g., adding a Trident backend, snapshots, backups).

I agree that there are many advantages to using CRDs, but there are also some advantages to directly interacting with etcd (as opposed to through the creation of CRDs and letting the Kubernetes API Server deal with etcd). For example, some Trident operations require atomic updates across multiple objects. There is no way one can do this sort of transactions using Kubernetes API objects or CRDs; however, this is possible with the direct use of the etcd client. Also, CRDs lack support for versioning (this might have changed recently).

I like how you've added the new "kubernetes" persistent layer. The truth is that we can't get rid of the etcd persistent layer as Trident will be used with other container orchestrators through our CSI implementation, so we can't solely be dependent on CRDs.

I'm not ruling out the use of CRDs, but for now we're mostly looking at them as mechanisms to enable new capabilities for k8s users.  Having said that, I'm open to this idea if all the issues are addressed. Do you have any plans for the following?

1. Migrating the existing state in etcd to CRDs
2. Transferring Trident state from one k8s cluster or namespace to another
3. Backing up the Trident state

Thanks,
-Ardalan

**Comment by kangarlou** [comment]
Thanks for the additional information! Good answers! :) I haven't gone through the latest code changes, but a couple of follow-up questions:

1. Why should objects be cluster-scoped and not limited to the `trident` namespace?
2. Trident already has some code to do the migration from etcdv2 to etcdv3: https://github.com/NetApp/trident/blob/b3163c122cb1f1662aaf64468c1cddd32762db6d/core/orchestrator_core.go#L72:L76. A similar approach can be used to handle migration from etcdv3 to CRDs.

However, my biggest reservation with moving away from etcd are some of our roadmap items (e.g., supporting multiple instances of Trident per k8s cluster, Trident instances working together across k8s clusters). These features are much easier supported through integration with an external KV-store that supports atomic transactions, locks, etc. than through the CRD implementation. 

I don't dispute the value of using CRDs for a single k8s cluster. However, that ease comes at the expense of losing some flexibility for more complicated use cases that we're planning to support. We need to understand all the ramifications of this transition and that's something that I'll be discussing with our team. Thanks again!

**Comment by kangarlou** [comment]
> The reason for cluster scoped was its where the data logically sits. Most of the config we are storing is for the whole cluster, storage class and backend configuration are prime examples of this. One may be tempted to use namespaces for data separation allowing the use of multiple Trident instances in cluster. However there are better solutions to this (labels for example) that would accomplish this better and allow multiple Trident instances to live in the same namespace if the operator wanted.

I agree with you that Trident operates on cluster-scoped resources and that multiple instances of Trident should reside in the same namespace. The main motivation for having multiple instances of Trident is to increase throughput and to a much lesser degree improve availability. So what I have in mind is that multiple instances of Trident are deployed in the `trident` namespace, all operating on cluster-scoped resources. How these instances divide the work is another topic, but the main motivation for namespace-scoped CRDs is that all artifacts of Trident are localized in the same namespace. This would make backing up Trident state easier (e.g., ark backing up everything in the `trident` namespace). Also, in some organizations Trident administrators are not the same as Kubernetes administrators, so having a namespace dedicated to Trident and all its artifacts would make life easier for Trident admins.

> By multiple instances of Trident per cluster, does this involve them sharing state? Correct me if i'm wrong, but Trident currently seems to keep most state in memory which would be difficult if you wanted to share state. If this involves separate state then labels/owner metadata can be used to ensure separation.

You're right. Today, Trident caches the state it maintains in etcd and that needs to change if there are multiple Trident instances operating on the same object (e.g., update to a Trident backend when a volume is added).

> By Trident instances working together across k8s clusters, do you mean multiple Tridents communicating or a single Trident administering multiple clusters? If the former then thats the primary use case of Kubernetes APIServer. Multiple components communicating through creating and watching for objects. If the latter then I agree it makes no sense to store state in CRDs. Thats why I am not proposing replacing etcd, just adding CRDs as an option for the basic use case.

There have been requests for both. I'm primarily interested in data movement between different Kubernetes clusters. Federated CRDs might be one viable solution but we're far from that and we would like to support this use case in near future. 

> Its worth noting that you can implement Mutexes using CRDs. To update an object in Kubernetes it uses the resource version to perform optimistic concurrency. This would allow atomic actions to be performed against Kubernetes state easily. I would be happy to fold that into my PR if it would help.

Yes, that can be useful based on the direction we decide. Resource versions are in fact how etcd handles concurrency and Kubernetes relies on the same mechanism. One limitation is that the scope of the mutex is limited to a single cluster, but that may be good enough for most cases.

Hopefully, my comments clarified some of the concerns. I'm open to any ideas you may have. As I said, I need to discuss these issues with the larger team. Thanks!

**Comment by korenaren** [comment]
@ThatsMrTalbot Thanks for this PR! We would like to talk to you about your code. Can you join our Slack team so we can direct message each other? netapp.io... DM Marty Turner. Thanks!

**Pull request closed without merging**
