### PR TITLE
Stop using the beta.kubernetes.io/os

### PR DESCRIPTION
**Pull request by pacoxu**
## Change description
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

### CODE REVIEW

**Comment by gnarl** [comment]
Hi @pacoxu, 

Please confirm that you have signed the [CCLA](https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md) in order to contribute to the project. 

I see that this change is being requested for many Kubernetes projects as "beta" is deprecated for beta.kubernetes.io/os and beta.kubernetes.io/arch labels. Thanks for opening the PR. If you are not interested in attribution please let us know and a GitHub issue can be opened.

**Comment by pacoxu** [comment]
> Please confirm that you have signed the [CCLA](https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md) in order to contribute to the project.

Signed.

**Comment by pacoxu** [comment]
> I see that this change is being requested for many Kubernetes projects as "beta" is deprecated for beta.kubernetes.io/os and beta.kubernetes.io/arch labels. Thanks for opening the PR. If you are not interested in attribution please let us know and a GitHub issue can be opened.

It is not a problem from the current latest Kubernetes v1.25 or v1.19~1.25.  I would be a problem probably in v1.27 or v1.28.(We plan to remove the deprecated one then.)

**Comment by pacoxu** [comment]
> First-time contributors need a maintainer to approve running workflows.

@gnarl Could you approve the test running?

**Comment by gnarl** [comment]
Hi @pacoxu, 

It doesn't appear that we ever received the [signed CCLA](https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md). The link for submitting the CCLA is in step 6.

**Comment by pacoxu** [comment]
Sign doc can be found in https://netapp.na1.adobesign.com/public/agreements/view/CBJCHBCAABAAU_o2rWIj074mjll1y-i7ORljohvn073l?type=esign&tsid=CBFCIBAA3AAABLblqZhASZoia1x3wfzkxG9mB2taFNRJxpxT-33vhS0kjmPpa1bMxzPyjagz3D_vw4D7zYrZxB9NKqF6uY_1a1gLlBipU

**Comment by gnarl** [comment]
@pacoxu, thanks for signing the CCLA and providing the link.

**Comment by gnarl** [comment]
Hi @pacoxu,

We had a change requirement that removed the use of a node selector in the section of code you'd modified. Because of this change we were unable to use your PR. Thank you for your contribution!

**Pull request closed without merging**
