### PR TITLE
Adding standard common helm chart values

### PR DESCRIPTION
**Pull request by julian3xl**
Signed-off-by: julian3xl <julian3xl@gmail.com>

Helm Chart is a mature packaging system that tries to establish a series of common methodologies so that the deployment of packages in a kubernetes cluster is as consistent as possible. Things like nodeSelector, affinity and so on are values that chart users should be able to choose.

### CODE REVIEW

**Comment by julian3xl** [comment]
Hi @adkerr , any chance to get this merged one day (at least reviewed). I'm mentioning you because you seem to be the most active netapp member. Thanks in advance.-

**Comment by adkerr** [comment]
Thanks, @julian3xl , I'll make sure our team reviews this.

**Comment by khassel** [comment]
any progress here? We need the `nodeAffinity` feature ...

**Comment by julian3xl** [comment]
yeah, they told me on slack that they will review it for 21.07 so I guess it will be in progress 🤷‍♂️

**Comment by gnarl** [comment]
Hi @julian3xl,

Have you submitted your [CCLA](https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md) yet?

**Comment by julian3xl** [comment]
> Hi @julian3xl,
> 
> Have you submitted your [CCLA](https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md) yet?

Apologies man, I didn't know that. Doing it right now.-

**Comment by julian3xl** [comment]
Hi @gnarl, I've already signed and submitted my CCLA. Thanks for your reminder.-

**Comment by julian3xl** [comment]
Hi @gnarl, any progress here? it has been a long time!

**Comment by igor-nikiforov** [comment]
Could anyone from maintainers please take a look at this PR and finally merge this?

**Comment by jpuskar** [comment]
Simple PR and would be helpful, hopefully y'all can review soon.

**Comment by jpuskar** [comment]
Oh but also, priorityClassName would be a good addition.

**Comment by julian3xl** [comment]
Yeah, probably. But to be honest I don't believe this PR will be merged ever. I don't see repo maintainers so interested on it.

**Comment by ameade** [comment]
I'll pull this in and run through our CI + internal reviews. Thanks for the patch, i'll report back

**Comment by ameade** [comment]
Found one small issue, fixed it. Will merge internally after a little testing.

**Comment by ameade** [comment]
This change has been added in the follow commit and will be included in the 22.01 release:
https://github.com/NetApp/trident/commit/84cdd03e54af27c08354cd4cf0bb91e3d3cf7a2e

**Pull request closed without merging**
