### PR TITLE
tridentctl: Improve error message when fails to execute kubectl

### PR DESCRIPTION
**Pull request by superbrothers**
tridentctl currently outputs "could not find the Kubernetes CLI" when
fails to execute kubectl even if kubectl command is found. With this PR,
tridentctl is changed to outputs the following error message if kubectl
is found but it exits with error:

```
$ bin/tridentctl version
Error: could find the Kubernetes CLI, but it exited with error: Unable
to connect to the server: No valid id-token, and cannot refresh without
refresh-token
```

### CODE REVIEW

**Comment by korenaren** [comment]
Hi @superbrothers - we finally have a [CONTRIBUTING.md](https://github.com/NetApp/trident/blob/master/CONTRIBUTING.md) file. Can you please take a look, and submit the CCLA if you are okay with it. Thanks!

**Comment by superbrothers** [comment]
Hi @korenaren, I'll check out it. Thanks!

**Comment by superbrothers** [comment]
@korenaren I signed your CCLA, and I've send the document!

**Comment by clintonk** [comment]
Thanks for the PR, @superbrothers!  We've merged your commit with proper attribution, so we can close this PR.

**Pull request closed without merging**
